# Generated by Django 5.2.14 on 2026-06-01 01:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("tag", models.CharField(default="", max_length=200)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("M1", "Marhale 1"), ("M2", "Marhale 2")],
                        max_length=20,
                    ),
                ),
                ("question_count", models.PositiveIntegerField(default=25)),
                ("pdf_file", models.FileField(upload_to="media/exams/pdfs/q/")),
                (
                    "answer_pdf_file",
                    models.FileField(default="", upload_to="media/exams/pdfs/a/"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("duration_lenght", models.IntegerField(default=120)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multi_choice", "5-Choice Question"),
                            ("true_false_set", "5-Boolean Statements"),
                            ("numeric", "Numeric Answer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("correct_answer", models.CharField(max_length=50, null=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Question order in exam"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exam.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("started_date", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_possible_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "percentage_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="exam.exam",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_exams",
                        to="personal.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "exam")},
            },
        ),
        migrations.CreateModel(
            name="ScoreBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "percentage_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("completed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoreboards",
                        to="exam.exam",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoreboard_entries",
                        to="personal.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["exam", "rank"],
                "unique_together": {("exam", "profile")},
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_value",
                    models.CharField(blank=True, default="-", max_length=10),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.question"
                    ),
                ),
                (
                    "user_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exam.userexam",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_exam", "question")},
            },
        ),
    ]
