# Generated by Django 5.2.14 on 2026-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
