# Generated by Django 5.2.14 on 2026-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_alter_exam_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="description",
            field=models.TextField(default="", max_length=255),
        ),
    ]
